### ISSUE TITLE
1.1.0 broken

### ISSUE THREAD

**Issue by callumacrae** [jnordberg/browsernizr#21]
```
Error: Cannot find module './../../lib/test/css/supports' from '[...]/node_modules/browsernizr/test/css'
   at [...]/node_modules/resolve/lib/async.js:55:21
   at load ([...]/node_modules/resolve/lib/async.js:69:43)
   at onex ([...]/node_modules/resolve/lib/async.js:92:31)
   at [...]/node_modules/resolve/lib/async.js:22:47
   at FSReqWrap.oncomplete (fs.js:95:15)
```

This is happening on multiple projects of ours. Looks like it was caused by #16 and renders the project completely unusable for us!

**Comment by Corentinfardeau** [comment]
Same issue...

**Comment by jnordberg** [comment]
I suggest holding your projects at version 1.0.2

Having a look now into getting the latest modernizr work node style. Guess this is what i get for trusting random people on the internet to review code. Would be interested to know if any of the people in #15 actually tested it...

**Comment by callumacrae** [comment]
Thanks :)

**Comment by jnordberg** [comment]
Published a new version now, should work. Let me know if you have any problems
